apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-operator
  labels:
    application: es-operator
    version: latest
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: es-operator
  template:
    metadata:
      labels:
        application: es-operator
        version: latest
    spec:
      containers:
      - name: es-operator
        image: registry.opensource.zalan.do/poirot/es-operator:latest
        args:
        - --pod-selector=application=es-cluster
        - --elasticsearch-endpoint=http://elasticsearch:9200
        - --priority-node-selector=lifecycle-status=ready
        resources:
          limits:
            cpu: 20m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 100Mi
